### ISSUE TITLE
What is the possibilities of submitting current Commits to Visual Studio's Marketplace ?? and Updating the Readme ??

### ISSUE THREAD

**Issue by Zorono** [Subtixx/vscode-mtalua#19]

**Comment by Subtixx** [comment]
I've tried multiple times to update it on the marketplace but its not allowing me to update it anymore since my access token expired half a year ago. You can still download the generated vsix and update it that way but until microsoft gets me access to my extension again, i'm afraid there is nothing I can do. Since the stupid support bot would not allow me to create a ticket..

Whats with the readme? Why do you think it needs updating?

**Comment by Zorono** [comment]
> Whats with the readme? Why do you think it needs updating?
- add your recent Changelog
- talk about your current situation with Marketplace Token...
- update The Project's Current update stats [`<p align="center"><img src="https://img.shields.io/maintenance/yes/2019.svg?style=flat-square"></p>`](https://github.com/Subtixx/vscode-mtalua/edit/master/README.md#L6)
- and please unlink those badges from the Marketplace's **Version** and **Downloads Count** [`<p align="center"><a href="https://marketplace.visualstudio.com/items?itemName=subtixx.mtasa-lua"><img src="https://img.shields.io/vscode-marketplace/v/subtixx.mtasa-lua.svg?style=flat-square" /></a><a href="https://marketplace.visualstudio.com/items?itemName=subtixx.mtasa-lua"><img src="https://img.shields.io/vscode-marketplace/d/subtixx.mtasa-lua.svg?style=flat-square" /></a><p/>`](https://github.com/Subtixx/vscode-mtalua/edit/master/README.md#L17-20)
TIP: Thanks for mentioning that `vsix` file from *Releases*

**Comment by RedCMD** [comment]
can you update your access token at https://dev.azure.com/Subtixx/_usersSettings/tokens
or maybe ask at https://github.com/microsoft/vsmarketplace
