### ISSUE TITLE
Parsing of custom functions

### ISSUE THREAD

**Issue by ZbyK77** [Subtixx/vscode-mtalua#23]
Hi,
Recently I switched from npp to vscode. I often use feature suggestions when i`m writing scripts, that's why I installed your extension. Unfortunately, after the install, the suggestions for words that are already in the file disappear.

![image](https://user-images.githubusercontent.com/65454704/114221336-7e09f980-996d-11eb-8500-36b55b8ee5b4.png)

![image](https://user-images.githubusercontent.com/65454704/114219848-7e08fa00-996b-11eb-8104-0d49681c53bd.png)

After switching from "MTA Lua" to "Lua" the other suggestions keep coming back, but there's no MTA function.

![image](https://user-images.githubusercontent.com/65454704/114220838-c7a61480-996c-11eb-91c7-ceb0271d3785.png)

I'd like to add that I've "Suggest: Show Words" set to true.
![image](https://user-images.githubusercontent.com/65454704/114221109-2c616f00-996d-11eb-85ec-3ad6d5f8f4ee.png)
Is it possible to combine these two functionalities?

**Comment by Subtixx** [comment]
This was already on the agenda years ago (#11 #13 #14). But since this plugin doesn't parse a file like the standard LUA Code completion explained [here](https://github.com/Subtixx/vscode-mtalua/issues/13#issuecomment-484803338) its not possible, and would require a whole rewrite of the entire plugin.
